
#ifndef GUARD_SMCPCORE_PYINTERPRETER_GLOBAL_CMNHDR_H
#define GUARD_SMCPCORE_PYINTERPRETER_GLOBAL_CMNHDR_H

#include "Decl.h"
#include <BedRock/Config.h>


#endif //GUARD_SMCPCORE_PYINTERPRETER_GLOBAL_CMNHDR_H