

#ifndef GUARD_SMCPCORE_BEDROCK_GLOBAL_NAMESPACES_H
#define GUARD_SMCPCORE_BEDROCK_GLOBAL_NAMESPACES_H

#include "../Config.h"

// Macros for namespace
// AdSim::BedRock
//
#define BEGIN_NAMESPACE_BEDROCK \
    SMCP_BEGIN_NAMESPACE(AdSim) \
    SMCP_BEGIN_NAMESPACE(BedRock)


#define END_NAMESPACE_BEDROCK \
    SMCP_END_NAMESPACE(AdSim) \
    SMCP_END_NAMESPACE(BedRock)

#endif // GUARD_SMCPCORE_BEDROCK_GLOBAL_NAMESPACES_H

