#ifndef GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_INTERNALNAME_H
#define GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_INTERNALNAME_H

#pragma once

#define SMCP_LIB_NAME			JavaScriptEngine
#define SMCP_LIB_DESCRIPTION	"This Library is for JavaScriptEngine.."

#endif // GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_INTERNALNAME_H
