#ifndef GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_NAMESPACES_H
#define GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_NAMESPACES_H

#pragma once

#include "Decl.h"


// Macros for namespace
// SolidMCP::JavaScriptEngine
//
#define BEGIN_NAMESPACE_JAVASCRIPTENGINE \
    SMCP_BEGIN_NAMESPACE(SolidMCP) \
    SMCP_BEGIN_NAMESPACE(JavaScriptEngine)

#define END_NAMESPACE_JAVASCRIPTENGINE \
    SMCP_END_NAMESPACE(SolidMCP) \
    SMCP_END_NAMESPACE(JavaScriptEngine)

#endif //GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_NAMESPACES_H
