#ifndef GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_TESTPROXY_H
#define GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_TESTPROXY_H

#pragma once

#include "Decl.h"
#include "Global.h"

BEGIN_NAMESPACE_JAVASCRIPTENGINE

class EXPORT_CORE_JAVASCRIPTENGINE TestProxy
{
public:
	static int Run();
};

END_NAMESPACE_JAVASCRIPTENGINE

#endif //GUARD_SMCPCORE_JAVASCRIPTENGINE_GLOBAL_TESTPROXY_H
