#ifndef GUARD_SMCPCORE_BEDROCK_CONFIG_COMPILER_VC_H
#define GUARD_SMCPCORE_BEDROCK_CONFIG_COMPILER_VC_H

#define SMCP_COMPILER_NAME "Microsoft Visual Studio C++"
#define SMCP_COMPILER_VERSION  _MSC_VER
#define SMCP_COMPILER_MSVC _MSC_VER


#endif // GUARD_SMCPCORE_BEDROCK_CONFIG_COMPILER_VC_H
