#ifndef GUARD_SMCPCORE_BEDROCK_SUPPORT_H
#define GUARD_SMCPCORE_BEDROCK_SUPPORT_H

// Support is about what features to enable and what features to have
// SMCP_HAVE_XXX
// SMCP_ENABLE_XXX
//

#define SMCP_HAVE_INT64

#define SMCP_ENABLE_EXCEPTION 1

#define SMCP_ENABLE_NAMESPACE 1

#define SMCP_ENABLE_DISABLEWARNINGS 1


#endif // GUARD_SMCPCORE_BEDROCK_CONFIG_H