
#ifndef GUARD_PLAYBOOST_GLOBAL_TESTPROXY_H
#define GUARD_PLAYBOOST_GLOBAL_TESTPROXY_H

#include "Decl.h"

BEGIN_NAMESPACE_PLAYBOOST

class EXPORT_CORE_PLAYBOOST TestProxy
{
public:
    static int Run();
};

END_NAMESPACE_PLAYBOOST

#endif //GUARD_PLAYBOOST_GLOBAL_TESTPROXY_H
